[build]
  command = "./build.sh"
  publish = "out"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"
  NODE_VERSION = "22"
  NODE_ENV = "development"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# This makes sure that all routes are directed to the index.html file
# which is necessary for client-side routing to work
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 