[build]
  command = "NODE_ENV=development npm ci && npm run build"
  publish = ".next"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"
  NODE_VERSION = "22"
  NODE_ENV = "development"

[[plugins]]
  package = "@netlify/plugin-nextjs" 