# Netlify configuration file
[build]
  # Directory where your project is located
  base = ""
  
  # Command to build your site
  command = "npm run build"
  
  # Directory that contains the deploy-ready files
  publish = ".next"
  
  # Default build environment variables
  environment = { NODE_VERSION = "18" }

# Use the NextJS plugin for Netlify
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Specify where functions are located
[functions]
  directory = "netlify/functions"
  
# Redirect all traffic to the Next.js app
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/nextjs-server"
  status = 200 